language: generic 
sudo: required
services:
  - docker

before_install: 
  docker build -t mhshukla9/docker-reactnew -f Dockerfile.dev
script:
  - docker run -e CI=true mhshukla9/docker-reactnew npm run test
