language: generic 
sudo: required

services:
  - docker

before_install: 
  - docker build -t mhshukla9/docker-reactms -f Dockerfile.dev .

script:
  - docker run -e CI=true mhshukla9/docker-reactms npm run test
    
deploy:
  provider: elasticbeanstalk
  region: "ca-central"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-ca-central-1-629659608621"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

