language: generic 
sudo: required
services:
  - docker

before_install: 
  - docker build  -f Dockerfile.dev -t mhshukla9/docker-reactms .
script:
  - docker run -e CI=true mhshukla9/docker-reactms npm run test
deploy:
  provider: elasticbeanstalk
  region: "ca-central"
  app: "Docker-reactnew"
  env: "Dockerreactnew-env"
  bucket: "elasticbeanstalk-ca-central-1-629659608621"
  path: "Docker-reactnew"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

